version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: very_secret_password
      MARIADB_USER: demo-user
      MARIADB_PASSWORD: my_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080